### ISSUE TITLE
cannot read property indexof of undefined

### ISSUE THREAD

**Issue by bvdbos** [athombv/com.wolframalpha#5]
Wolfram was deleted from the appstore. Downloaded it from
https://github.com/athombv/com.wolframalpha
but running gave:

`TypeError: Cannot read property 'indexOf' of undefined
    at /app.js:77:16
    at /node_modules/node-wolfram/dist/index.js:46:20
    at Parser.<anonymous> (/node_modules/xml2js/lib/xml2js.js:484:18)
    at emitOne (events.js:77:13)
    at Parser.emit (events.js:169:7)
    at Object.onclosetag (/node_modules/xml2js/lib/xml2js.js:445:26)
    at emit (/node_modules/sax/lib/sax.js:639:35)
    at emitNode (/node_modules/sax/lib/sax.js:644:5)
    at closeTag (/node_modules/sax/lib/sax.js:903:7)
    at Object.write (/node_modules/sax/lib/sax.js:1444:13)

--- INFO: com.wolframalpha.knowledge has been killed ---`

Tried adding some console.log's but didn't see what goes wrong? Guess it's not just me, anyone got this working?

**Comment by bvdbos** [comment]
ping? As far as I can tell this issue shouldn't be hard to fix?

**Comment by RobinBol** [comment]
Currently we are not actively supporting this app, we might again in the future. I'll keep this issue open as a reminder.

**Comment by RobinBol** [comment]
Moved to: https://github.com/athombv/homey/issues/1985
